### ISSUE TITLE
The player can flip a coin.

### ISSUE THREAD

**Issue by Toltar** [HarambeStudios/Project-Spacetime#8]
## Subissues
#9 
#10 
#11

**Comment by samplenr** [comment]
The HUD currently has a coin icon, that when pressed will play the coin flip audio as well as animate a coin flip. I am having trouble returning the HUD to a state where it can be interacted with after however. I need to figure out some sort of wait command to wait for the animation to play out, and then return the animation state to false so it can be reused. Figuring out this wait issue will also allow lead to a method to hide and show the coin as appropriate for animation purposes rather than being a permanent fixture on screen or permanently hidden.

**Comment by samplenr** [comment]
The HUD branch has been updated, the coin flip now shows and hides properly when the button is pressed on the HUD.

**Comment by LeviDooley** [comment]
The coin now flips every time the player splits.
